version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: userserv
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080